### PR TITLE
ROS bags player

### PR DESCRIPTION
**Pull request by HemaZ**
Hello, 
I`ve added some basic functionality for playing ROS bags #13 

`import jupyros as jr`
`jr.bag_player()`

then write the ros bag path and experiment with the shown fields.
this part of ROS wiki is useful to understand the differnet arguments.
http://wiki.ros.org/rosbag/Commandline#play
Screenshot-20190415214614-1073x524

### CODE REVIEW

**Comment by wolfv** [comment]
Hi @HemaZ 

wow! That's awesome work! Really nice :)

Only thing I am wondering is wether it's the best approach to use subprocess to control the bag playing?! 

One can also do `import rosbag` and then call a lot of functions for reading, and analzying of the rosbags from within Python.
We can also take a look at rqt_bag (https://github.com/ros-visualization/rqt_bag/blob/master/rqt_bag/src/rqt_bag/player.py ) and we might even be able to reuse some of the code?

What do you think about this alternative approach?

**Comment by HemaZ** [comment]
Hello @wolfv 
I think using the rosbag play command is better than reimplementing this in python.
https://github.com/ros/ros_comm/blob/indigo-devel/tools/rosbag/src/play.cpp 
the play command is already implemented in c++. I believe reimplementing the same functionality in python would give worse performance specially if you are playing large bag files with complex messages like images and point clouds. We could definitely use rosbag python API in other features. like inspecting or editing the bag. but for play, I think using the rosbag play would be better.

**Comment by wolfv** [comment]
Ok, I understand your reasoning. I am not sure what the performance of the same in Python would be, but I see that running it in a thread could make "accurate" timed replay somewhat difficult.

I am happy to merge this as is. If you are interested in working a little further on this, it would be cool to implement a callback on comms close so that when the widget is removed, it will stop the bag playing subprocess as well.
Let me know

**Comment by HemaZ** [comment]
Would love to do this but I can't find any reference in ipywidgets documentation. 
do you have any examples or tips regarding this? 
what I can think of is saving the subprocess in a global variable and close it on new widget construction. but I think there might be a better solution.

**Comment by wolfv** [comment]
Ok, I also checked briefly and didn't find a solution ... i asked on the jupyter widgets gitter channel. Let's see.

One last request: it would be cool to add a argument to the bag player to choose the file. E.g. bag_player('my_bag.bag') should either prefill the field or remove the bag file field :)

**Comment by HemaZ** [comment]
@wolfv  Done :+1:

**Comment by wolfv** [comment]
Cool! congrats :)

**Comment by HemaZ** [comment]
Thanks. Glad to help :)

**Pull request merged**
