### PR TITLE
Fix #144

### LINKED ISSUE #144: error with "jupyter nbextension install --py --symlink --sys-prefix jupyros"
when I run "jupyter nbextension install --py --symlink --sys-prefix jupyros" , it breaks down for the following error. My environment is python 3.9 and it seems python3.x do not support the Unicode function. Hope to get some clues!!!!
```
 File "/jupyter-ros/jupyros/ros1/ros3d.py", line 73, in ROSConnection
    url = Unicode(os.environ.get("JUPYROS_WEBSOCKET_URL", "ws://Z9d2n4:9090")).tag(sync=True)
NameError: name 'Unicode' is not defined
```

### PR DESCRIPTION
**Pull request by Andor233**

### CODE REVIEW

**Comment by hbcarlos** [comment]
Thanks @Andor233!

**Review by ihuicatl — APPROVED** [review]
Good catch!

**Comment by Andor233** [comment]
Sorry I am not familiar with your build system, what's going wrong with it?

**Comment by Andor233** [comment]
And I find that it already not pass in your past commit

**Comment by hbcarlos** [comment]
Hi @Andor233! Sorry for the delay!

I took the liberty to rebase your PR to pick the CI fix from main. Thank you so much for your contribution!

**Pull request merged**
