### PR TITLE
Initial class restructuring of jupyter-ros2

### PR DESCRIPTION
**Pull request by zmk5**
Instead of relying on functions to do most of the actions, I've attempted to switch things over to classes. This will allow people to create their own GUIs by inheriting the Subscriber or Publisher class for their own GUIs.

### CODE REVIEW

**Comment by zmk5** [comment]
Sorry, meant to merge this with my repository!!

**Comment by wolfv** [comment]
hey zmk5, no worries! 

Let's dicscuss getting this into this main repo, I'd be excited about it! I am going to take a look at your changes right now.

**Comment by wolfv** [comment]
Looks like very good work. Do you want to keep your own repo or become a collaborator on this one? 
We could make either a ROS 2 branch, or we could try to support ROS 1 and 2 at the same time? Do you think that would be feasible?

**Comment by zmk5** [comment]
Thanks! I'm not sure, I had plans to change some stuff around and kind of make it a bit different than the original jupyter-ros. RoboStack is your organization right? If so, maybe we can move it as a separate project within this?

**Pull request closed without merging**
